name: Build and Release Windows Executable

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  PROJECTNAME: PROJECTNAME
  PROJECTNAME_WINDOWS: PROJECTNAME-Windows.exe
  PROJECTNAME_MACOS: PROJECTNAME-MacOS
  PROJECTNAME_LINUX: PROJECTNAME-Linux

permissions:
  contents: write

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: CMke Setting
        run: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -B build

      - name: Compile with Clang
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: build/${{ env.PROJECTNAME_WINDOWS }}

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: CMke Setting
        run: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -B build

      - name: Compile with Clang
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: build/${{ env.PROJECTNAME_MACOS }}

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: CMake Setting
        run: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -B build

      - name: Compile with Clang
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: build/${{ env.PROJECTNAME_LINUX }}

  release:
    needs:
      - build_windows
      - build_macos
      - build_linux
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
          path: .

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-artifact
          path: .

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-artifact
          path: .

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.PROJECTNAME_WINDOWS }},${{ env.PROJECTNAME_MACOS }},${{ env.PROJECTNAME_LINUX }}"
          tag: ${{ inputs.tag }}